<?php

namespace CTE\AccueilBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CTEController__JMSInjector
{
    public static function inject($container) {
        $instance = new \CTE\AccueilBundle\Controller\CTEController();
        return $instance;
    }
}
