parameters:
#    cte_accueil.example.class: CTE\AccueilBundle\Example

services:
#    cte_accueil.example:
#        class: %cte_accueil.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
